### ISSUE TITLE
Upgrade javafx-maven-plugin for Linux compliance

### ISSUE THREAD

**Issue by jcarsique** [dportabella/DesktopKeyboard2Android#1]
The javafx-maven-plugin must be upgraded to get a working Debian installer.

**Comment by alban-auzeill** [comment]
Thanks Julien. I think David is still lost in Nepal, so I have reviewed and merge your pull request myself.
The Debian package works fine on Ubuntu 14.04. I have tested the following commands:

``` sh
mvn jfx:native # ok
sudo dpkg -i target/jfx/native/desktopkeyboard2android-1.1.deb # ok
/opt/DesktopKeyboard2Android/DesktopKeyboard2Android # ok
# Start from the new DesktopKeyboard2Android menu ok
sudo dpkg -r desktopkeyboard2android # ok
```

**Comment by dportabella** [comment]
thanks guys!
yes, still in nepal, not in the mountains anymore, but still trapped with my broken laptop, daily power cuts, and since two months ago, with shortage of petrol for transportation and gas for cooking because of a political war with india.
i've added feature requests and help wanted to this project, in case you or your friends want to collaborate. :)
