### ISSUE TITLE
How to reset the Sequence key?

### ISSUE THREAD

**Issue by vekhuya** [dportabella/DesktopKeyboard2Android#6]
I try Desktop Keyboard 2 Android-release-1.0 very excited, thank dportabella! However when used to copy / paste multiple times through the application, it forced to reboot the computer and my android.
The problem may be in source code "int keySequence ++" in the URL "http://localhost:7777/key?" + keySequence + "," + keyEventString + ",". Value 32bit largest so how to reset?
Thank you explaining to me!

**Comment by dportabella** [comment]
The problem is that the connection between the computer and the Android fails (and automatically reconnects) from time to time, and the WifiKeyboard Android app uses a mandatory sequence. When this happens, the "fastest" thing to fix it is to touch only the Android phone as follows: change the keyboard input from WifiKeyboard to something else (eg Samsung keyboard) using the Android top bar menu, stop the WifiKeyboard app, then restart the app and reselect the WifiKeyboard keyboard (eventually, restart the DesktopKeyboard2Android application on your computer). Very painful, but you shouldn't need to restart the computer nor the Android.

This issue could be solved by reimplementing this application using adb api (which does not require a sequence) instead of the WifiKeyboard app. It's explained here. I am still traveling with my laptop broken, so I cannot work on it. Help wanted :)
https://github.com/dportabella/DesktopKeyboard2Android/issues/4
